<!-- <div class="vendor-banner"> -->
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Vinsol_MultiVendorMarketplace::css/styles.css'); ?>">  

<!-- <img class="banner" src="<?php //echo $block->getViewFileUrl('images/' . $block->banner . ''); ?>" alt="vendor-banner"/> -->     
 <img clas="banner" src="<?php echo $block->getImageUrl(); ?>" alt="vendor-banner"/>
<!-- </div> -->