<div class="logo-username-container">
  <!-- <div class=""> -->
<!--       <img class="logo" src="<?php //echo $this->getViewFileUrl('images/' . $this->logo . ''); ?>" alt="vendor-logo"/> -->
<!--       <img class="logo" src="<?php //echo $this->getLocation() . '/marketplace/images/' . $this->logo; ?>" alt="vendor-logo"/> -->
      <div class="vendor-logo">
<!--         <img class="logo" src="<?php //echo $block->getLocation() . '/mage2/pub/media/marketplace/images/' . $block->logo; ?>" alt="vendor-logo"/>
 -->
         <img class="logo" src="<?php echo $block->getImageUrl(); ?>" alt="vendor-logo"/>      
      </div>
      <div class="username"><?php echo $block->username; ?></div>
  <!-- </div> -->
</div>