<!-- <span style="font-weight: 400;">This is custom vendor view.</span> -->
<!-- <div style="background-repeat: no-repeat; background-image: url('../web/images/watami-banner.jpg'); width: '100%'; border: 2px solid black;"> -->
<!-- <div>
  <div class="vendor-banner">
    <img class="banner" src="<?php //echo $this->getViewFileUrl('Vinsol_MultiVendorMarketplace::images/watami_banner.jpg'); ?>" alt="vendor-banner"/>
  </div>
  <div clas="vendor-logo">
    <p>
      <img clas="logo" src="<?php //echo $this->getViewFileUrl('Vinsol_MultiVendorMarketplace::images/watami-logo.png'); ?>" alt="vendor-logo"/>
      <span class="vendor-name">Watami</span>
    </p>
  </div>
</div> -->
<!-- <link rel="stylesheet" type="text/css" href="<?php //echo $this->getViewFileUrl('Vinsol_MultiVendorMarketplace::css/styles.css'); ?>">   -->