<!--@subject {{trans "New order!"}}  @-->
<!--@styles
body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
@-->
<table>
  <tr>
    <td>
      <p>
        <h2>{{trans "Greetings %vendorName." vendorName=$vendorName}}</h2>
      </p>
      <p>
        {{trans "Your product(s) just got purchased by %customerName" customerName=$customerName}} 
        {{trans "(Email : %customerEmail)." customerEmail=$customerEmail}}
        {{trans "Please login to your account to view order details and generate invoice and/or release shipments." }}
      </p>
    </td>
  </tr>

  <tr>
    <td>
      <h3>{{trans "Order Id : #%orderId" orderId=$orderId}}</h3>
    </td>
  </tr>

  <tr>
    <!-- <table>
      <tr>
        <th>{{trans "Product"}}</th>
        <th>{{trans "Qty"}}</th>
      </tr>
      <?php foreach($products as $product): ?>
      <tr style=" align:center; valign:top; padding:20px 0 20px 0; bgcolor:#EAEAEA; ">
        <td><?php echo $product->getName(); ?></td>
        <td><?php echo $product->getQtyOrdered(); ?></td>
      </tr>
      <?php endforeach; ?>
    </table> -->
    <p>
      {{trans "Products : %productNames." productNames=$productNames}}
    </p>
  </tr>
</table>