<?php
/**
 * Product additional attributes template
 * 
 * IF THE CURRENT PRODUCT BELONGS TO AN ACTIVE VENDOR (i.e. product has additional attribute `user_id` ), 
 * THE VENDOR'S USERNAME IS A LINK TO VENDOR'S PRODUCT LISTING PAGE.
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    $_vendor = $block->getVendorCollection();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= __('More Information') ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data): ?>
                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml(__($_data['label'])) ?></th>
                    <td class="col data" data-th="<?= $block->escapeHtml(__($_data['label'])) ?>">
                        <?php 
                            if($_data['code'] === 'user_id') {
                                $_vendor->addAttributeToFilter('username', $_data['value'])->addAttributeToFilter('is_active', '1')->load();
                                if (count($_vendor->getLoadedIds())): ?>
                                    <a href="<?= $block->getUrl('vendors/vendors/index/', ['id' => $_vendor->getData()[0]['entity_id']]) ?>">
                                        <?= $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                                    </a>
                                <?php else: ?>
                                    <?= $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                                <?php endif; 
                            } else { ?>
                            <?= $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                        <?php } ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>
